### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by kiquenet** [Ahoo-Wang/SmartSql#4]
Good, but it would be better with very good documentation, all English, full samples with source code, and many samples.

Can I call stored procedure using SmartSql ?

Great

**Comment by Ahoo-Wang** [comment]
I'm sorry to say that the demand for SmartSql English documents and samples has not kept up with user demand since the recent work has been too busy. I'll try my best to take the time to sort out the relevant English documents. My English level is limited. If I have enough vocabulary, please help me improve.

In addition, SmartSql does not support stored procedures for the time being, and although I do not recommend using stored procedures, I will support this feature in the next release of SmartSql.

Finally, thank you very much for your support for SmartSql.

**Comment by Ahoo-Wang** [comment]
https://doc-en.smartsql.net/
